[package]
org = "embedded-alerts"
name = "eal-web-server"
version = "0.1.0"
description = "Rust web server for Embedded Alerts"
license = "MIT"
language = "rust"

[package.repository]
vcs = "git"
url = "https://github.com/embedded-alerts/eal-web-server.rs"

[install]
dir = ".vendor/.zed"

[dependencies]
"shared-auth/shared-auth-clients" = "^0.1.0"
"oresoftware/next-loggers" = "^0.1.0"

[build]
command = "cargo build --release --locked"
outputs = ["target/release/eal-web-server"]

[targets.rust]
dir = "."
adapter = "rust"

[publish]
include_readme = true
tag_format = "v{version}"
exclude = [".env", ".env.*", "node_modules/**", "target/**", "dist/**", "*.log", ".vendor/.zed/**"]
